### PR TITLE
Copied PR ueokande/vim-vixen#1437

### PR DESCRIPTION
**Pull request by jiriks74**
I simply copied ueokande/vim-vixen#1437 so that it can be merged and dealing with unmaintained plugin can be done here.

Maybe turn on discussions and let's `discuss` it there? Or create an issue?

I'm willing to figure out whether I could upload the plugin to Firefox Addons, but I'm not at the dev level to actively code it. I'll try to help with the best of my abilities and availability, but I don't promise anything.

So what's the next move?

PS: So that noone forgets, the credit for this patch goes to @jessarcher

### CODE REVIEW

**Review by LordPax — APPROVED** [review]
i think it's ok, thank you

**Comment by codeDude64** [comment]
How can I use this fork in my firefox?

**Comment by victorz** [comment]
> How can I use this fork in my firefox?

Well one way for the time being would be to install the add-on from your local drive rather than from the add-ons web "store". I'm on my phone right now but there's plenty of guides surely on how to do this, or perhaps someone who knows more details could write a comment, or put the instructions in the readme for now until we have it in the store again.

**Comment by LordPax** [comment]
> How can I use this fork in my firefox?

it's explain here
https://github.com/ueokande/vim-vixen/pull/1437#issuecomment-1176124720

**Pull request merged**
